function planManager:updateImpossibleStateForCraftAreaAvailibilityChange(craftAreaTribeID, objectID, craftAreaGroupTypeIndex, isNewlyAvailableOrNilForNewlyUnavailable, craftAreaObjectPos)
    updateImpossibleStateForCraftAreaAvailibilityChangeInternal(craftAreaTribeID, objectID, craftAreaGroupTypeIndex, isNewlyAvailableOrNilForNewlyUnavailable, craftAreaObjectPos)
end