function planManager:updateImpossibleStateForStorageAvailibilityChange(storageAreaTribeID, objectID, objectTypeIndex, isNewlyAvailable)
    updateImpossibleStateForStorageAvailibilityChangeInternal(storageAreaTribeID, objectID, objectTypeIndex, isNewlyAvailable)
end